<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>HyMT2Sharp.Server</RootNamespace>
    <AssemblyName>HyMT2Sharp.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HyMT2Sharp.Model\HyMT2Sharp.Model.csproj" />
    <ProjectReference Include="..\HyMT2Sharp.Gguf\HyMT2Sharp.Gguf.csproj" />
  </ItemGroup>
</Project>
